# Generated by Django 3.2.3 on 2021-05-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_education_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='link',
            field=models.CharField(default='link', max_length=255),
            preserve_default=False,
        ),
    ]
