# Generated by Django 3.2.3 on 2021-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_experience_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('short_descr', models.TextField()),
                ('techs', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('long_descr', models.TextField(verbose_name=models.TextField())),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
