# Generated by Django 3.2.3 on 2021-05-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='techs',
        ),
        migrations.AlterField(
            model_name='project',
            name='long_descr',
            field=models.TextField(default=models.TextField()),
        ),
    ]
